info:
  version: '0.1'
  title: 'new environment'
servers:
  - url: http://localhost:3000
    description: Development server(loopback)
  - url: http://192.168.1.187:3000
    description: Dev server(LAN)
paths:
  /api/user:
    get:
      parameters: []

      responses:
        '200':
          description: users list
          content:
            'application/json':
              schema:
                type: 'object'
              example:
                - users:
                  - id: 1
                    name: 'taro'
                  - id: 2
                    name: 'jiro'


openapi: 3.0.0
